### ISSUE TITLE
Scoped Directory Access support

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#140]
Not sure but just realized.

http://developer.android.com/preview/features/scoped-folder-access.html
https://github.com/googlesamples/android-ScopedDirectoryAccess

**Comment by aurae** [comment]
We should keep support for this in mind once the final SDK for N is released.

Some info on the methods used here: `StorageManager#getPrimaryVolume` has been added to the platform with `JELLY_BEAN_MR1`/Android 4.2, but has been marked with `@hide` ever since. `StorageVolume#createAccessIntent` is a new API coming with N, however.

It shouldn't be hard to add support for this within the library, as it is simply yet another special case for permissions. It baffles me why they wouldn't just extend the existing permissions model, but whatever.

**Comment by hotchemi** [comment]
It's been two over two years but seems not one is hoping this feature? 🤔

**Comment by hotchemi** [comment]
let me close for the time being!
