### ISSUE TITLE
[Proposal] Move permissions dispatcher related repos to an organization

### ISSUE THREAD

**Issue by hotchemi** [permissions-dispatcher/PermissionsDispatcher#353]
## Overview

@shiraji @aurae @AleksanderMielczarek

Hello contributors!
First of all I'm really appreciated for your dedicated work and creating consequential neat libraries😄

As seeing the growth of the library I'v been feeling like **it would be better to create an organization of PermissionsDispatcher and collect related libraries to one org**.

### Motivation

The biggest reason I'm feeling like so is that **it's not just my product anymore**.
Say, you guys respond to an issue pretty much nicely and continue to enhance/bug fix of products quite a lot.

So I'd like to give you the same commit/lead authority, and I'd like to have a responsibility to maintain consequential libraries as well.

### What would be changed?

- Move https://github.com/hotchemi/PermissionsDispatcher, https://github.com/shiraji/permissions-dispatcher-plugin, https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin to under `PermissionsDispatcher` organization(the name is not decided yet).
- You would have the same level of commit/lead the projects equally

Just in case, I'm not going to leave the projects of course.
Just want to make sure that give you a gratitude attitude sincelery and make maintainer system more decent one.

Note that this proposal is still just a proposal from my aspect so give your thought folks! 🙇

**Comment by shiraji** [comment]
This is wonderful!

I would like to transfer permissions-dispatcher-plugin to the org (whereas the project code is so messed up)

Some really little things I concern about are:

* Will we change the project name `com.github.hotchemi` to something?
* Will I need to change the author of plugin? I mean I want to but I don't know how to do it.

**Comment by hotchemi** [comment]
@shiraji Thank you!

> Will we change the project name com.github.hotchemi to something?
> Will I need to change the author of plugin? I mean I want to but I don't know how to do it.

Basically, I don't have a strong opinion for that. I mean, it would be better to keep a consistency of each products but on the other hand it may confuse user to update our library and plugin.
So in short, I think it's ok not to change artifactId and each platform's author info. If we're gonna do that it's not urgent(But it'd be beneficial to automate release task to reduce the burden 😂).

What do you think? 😺

**Comment by shiraji** [comment]
Since user doesn't care if the repo is in org or private, I agree what you suggest. 

> (But it'd be beneficial to automate release task to reduce the burden 😂)

As for my plugin, I created the automated release [scripts](https://github.com/shiraji/permissions-dispatcher-plugin/blob/master/.travis/after_success.sh) and [document](https://github.com/shiraji/permissions-dispatcher-plugin/blob/master/RELEASING.md). So, if I'm not able to release the new version, anyone who can have commit permission can release it.

**Comment by aurae** [comment]
I also agree that the PermissionsDispatcher "brand" would benefit greatly from a unified access point within Github, in the form of an organization. So we can definitely move the library & integration plugins by shiraji-san and Aleksander together in that regard, I'd say. Because I'm only familiar with the main library's scope and implementation, I'm unsure about the extent that I could assist with development and issues inside the plugin's repositories, though. Still, having it under the same umbrella is a good way to proceed for us in my opinion.

**Comment by AleksanderMielczarek** [comment]
Hello,

I like this idea. 

AA plugin currently doesn't use any CI and artifacts are hosted on JitPack. I suppose it should change and be unified with other products. 

As for artifact name change I agree with that it can lead to potential problems.

**Comment by hotchemi** [comment]
Thx guys! then I'll create org(and prepare nice icon) and announce here!

**Comment by hotchemi** [comment]
sorry for the late, here! https://github.com/permissions-dispatcher

**Comment by hotchemi** [comment]
I'll close this issue after all repos are moved.

**Comment by AleksanderMielczarek** [comment]
@hotchemi last repo just moved 😃

**Comment by hotchemi** [comment]
@AleksanderMielczarek Thx!
