### ISSUE TITLE
Gradle‘s daemon leak

### ISSUE THREAD

**Issue by fanmingyi** [permissions-dispatcher/PermissionsDispatcher#664]
https://github.com/gradle/gradle/issues/12571

Similar problems:https://github.com/google/dagger/issues/1645

**Comment by hotchemi** [comment]
thx, do you have more insights? checked dagger's PR but I'm not super familiar around there.. 🤔 @fanmingyi

**Comment by mannodermaus** [comment]
From what I can gather by looking at the referenced issues, it seems like there is a memory leak within kapt when certain static caches or utilities are being used. In our case, the culprit seems to be [this guy](https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/a4eb825cff6da6075b6d09a4eb035a665c95d953/processor/src/main/kotlin/permissions/dispatcher/processor/PermissionsProcessor.kt#L20-L21).

![Screen Shot 2020-03-25 at 10 04 11](https://user-images.githubusercontent.com/3897705/77519721-46263600-6e80-11ea-99d2-631bd5de7033.jpg)

`ELEMENT_UTILS` is only used by a singular helper function. Maybe it's possible to rid ourselves of that static reference, which should in turn allow for proper GC.

**Comment by bopbi** [comment]
this issue is solved by update the gradle to 4.0.0 and the kotlin version

` classpath 'com.android.tools.build:gradle:4.0.0'`

**Comment by hotchemi** [comment]
ref: https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/743
let me close the issue.
