### ISSUE TITLE
[Question] Why PermissionsRequestFragment set the ScreenOrientation to unspecified?

### ISSUE THREAD

**Issue by wakwak3125** [permissions-dispatcher/PermissionsDispatcher#673]
## Overview
The `ScreenOrientation` config is reset on close PermissionRequest dialog.
Before I use PermissionsDispatcher-ktx, I used kapt version of PermissionsDispatcher, this issue not happened.

So I try to search the root cause, I found a problem that `PermissionsRequestFragment` set the ScreenRotation to unspecified.

Is this an expected behavior? If not, I'll make PR.

### Expected

- The ScreenRotation will not change by PermissionsDispatcher-ktx.

### Actual

- The ScreenRotation changed by PermissionsDispatcher-ktx.

## Environment
- PermissionsDispatcher-ktx: 1.0.0-alpha02
- Pixel3, Android10 and Essential Phone Android9

**Comment by hotchemi** [comment]
Thank you so much for pointing out(I have been scared to get feedback for that actually haha). 
Actually I added that _reluctantly_ because when onConfigurationChanged occurs the caller Activity/Fragment is recreated and the references for that(onShowRationale: ShowRationaleFunc, onPermissionDenied) becomes inactive thus we can't reach out anymore.

Since I agree that the current workaround is incomplete and ugly I've been slowly considering how to deal with it w/screen orientation lock. Let me know your insights if you have something🙇

**Comment by wakwak3125** [comment]
Thanks for replying :pray: 
I see.. that a difficult problem...

This just came to my mind, how about saving/restore the original settings of the screen orientation flags instead of setting to `unspecified`?

Locking the screen orientation is not so bad I think.

**Comment by hotchemi** [comment]
Thank you for your suggestion! I'll take a look at this weekend and will let you know once I've got some updates here.

**Comment by hotchemi** [comment]
um..if we can have a restriction like `ActivityResultContracts.RequestPermission` then it's possible to deal with but then we can't use the API for handing click event or like that. um🤔 

https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts.RequestPermission

> You must always call prepareCall() in the same order for each creation of your fragment or activity to ensure that the inflight results are delivered to the correct callback.

**Comment by hotchemi** [comment]
This issue has been resolved in https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/678 and beta1 is out!
thank you for the feedback!
